### ISSUE TITLE
我测试insert一直不成功，能麻烦写一个insert的示例吗？

### ISSUE THREAD

**Issue by 102286545** [qieangel2013/EsParser#4]
如题。

**Comment by 102286545** [comment]
我找到原因了：
EsParser.php 里面的 resdata 方法对值的判断有问题：
将：  if($vv['base_expr']){  **** }
改成：  if(strlen($vv['base_expr'])){  ****   }
即可解决问题。

原因是如果插入的某个字段的值是数字0就不会进入判断。

**Comment by qieangel2013** [comment]
已修改，谢谢反馈！
